### PR TITLE
Fix mapMaybe and mapEither

### LINKED ISSUE #110: mapMaybe and mapEither are completely wrong
It looks like someone took (very clever; rather tricky to understand) code for `filter` and `partition` (which would also work for the plain `mapMaybe` in the `Prio` case) and generalized it to `mapMaybe`, `mapEither`, `mapMaybeWithKey`, and `mapEitherWithKey`. Unfortunately, the generalization is totally bogus; the order of keys in the result is not, in general, related to the order of keys in the argument.

### PR DESCRIPTION
**Pull request by treeowl**
* Fix incorrect behavior of `mapMaybe` and `mapEither` for `MinQueue`.

To do:

- [x] Add tests.
- [x] Port all these changes to `MinPQueue`.

Fixes #110.

### CODE REVIEW

**Comment by treeowl** [comment]
To do:

- [ ] Add tests.
- [ ] Port all these changes to `MinPQueue`.
- [ ] Port the new `Monotonic` functions to `MaxQueue` and `MaxPQueue`, with `Antitone` names.

**Comment by treeowl** [comment]
Another thing: we should verify that the monotonic versions are actually faster than the simple ones. That's not even slightly obvious to me. They're extremely hard to understand. At first, I thought they were structured to avoid unnecessary comparisons, but looking at them more closely, that doesn't seem to be the case.

**Comment by treeowl** [comment]
Ah, but maybe it could be made so? I have to think this over....

**Comment by treeowl** [comment]
I fixed the monotonic code to take what advantage it can of the ordering. However, it was still significantly (although modestly) slower than just using plain old `mapMaybe` and `mapEither`. So let's not add these monotonic specials, and just do the simplest possible thing. Less code, less error prone, and faster sounds like a nice trifecta to me.

**Comment by treeowl** [comment]
@konsumlamm, would you please try to review this soon?

File: src/BinomialQueue/Internals.hs [hunk 1]
```diff
@@ -219,11 +227,17 @@ unions = foldl' union empty
...
-mapMaybe f (MinQueue ts) = mapMaybeQueue f (const empty) empty ts
+mapMaybe f = flip foldlU' empty $ \q a ->
+  case f a of
+    Nothing -> q
+    Just b -> insertEager b q
 
 -- | \(O(n)\). Map elements and separate the 'Left' and 'Right' results.
 mapEither :: (Ord b, Ord c) => (a -> Either b c) -> MinQueue a -> (MinQueue b, MinQueue c)
-mapEither f (MinQueue ts) = mapEitherQueue f (const (empty, empty)) (empty, empty) ts
+mapEither f = (fromPartition .) . flip foldlU' (Partition empty empty) $ \(Partition ls rs) a ->
```
Comment (konsumlamm) [inline src/BinomialQueue/Internals.hs:237]: Can we please avoid `(f .) . g`? I find that hard to understand.

File: src/BinomialQueue/Internals.hs [hunk 2]
```diff
@@ -666,6 +661,7 @@ foldlU f z (MinQueue ts) = foldl_ f z ts
 -- @since 1.4.2
 foldlU' :: (b -> a -> b) -> b -> MinQueue a -> b
 foldlU' f z (MinQueue ts) = foldl'_ f z ts
+{-# INLINE foldlU' #-}
```
Comment (konsumlamm) [inline src/BinomialQueue/Internals.hs:664]: Did you check that this improves things?

File: src/BinomialQueue/Internals.hs [hunk 3]
```diff
@@ -209,6 +210,13 @@ singleton x = MinQueue (Cons (tip x) Nil)
 insert :: Ord a => a -> MinQueue a -> MinQueue a
 insert x (MinQueue ts) = MinQueue (incr (tip x) ts)
 
+-- | \(O(\log n)\), but a fast \(O(1)\) average when inserting repeatedly in
+-- an empty queue or at least around \(O(\log n)\) times into a nonempty one.
+-- Insert an element into the priority queue. This is good for 'fromList'-like
+-- operations.
```
Comment (konsumlamm) [inline src/BinomialQueue/Internals.hs:216]: Should we also use it in `fromList`-like functions then? Or do you want to do that in a future PR?

File: src/BinomialQueue/Internals.hs (hunk 2 above)
Comment (treeowl) [reply src/BinomialQueue/Internals.hs:664]: That was actually a mistake, and won't change anything at all. I'll remove it.

File: src/BinomialQueue/Internals.hs (hunk 3 above)
Comment (treeowl) [reply src/BinomialQueue/Internals.hs:216]: We currently tend to inline it, but yes, I'd like to hunt those down.

File: src/BinomialQueue/Internals.hs (hunk 1 above)
Comment (treeowl) [reply src/BinomialQueue/Internals.hs:237]: Yeah, I suppose I can expand the whole thing out.

Comment (treeowl) [reply src/BinomialQueue/Internals.hs:237]: Or would you be happy with `(fromPartition .) $ flip ...`?

Comment (konsumlamm) [reply src/BinomialQueue/Internals.hs:237]: I think it would be better to just expand it to a lambda, that would be easier to understand.

File: src/BinomialQueue/Internals.hs (hunk 3 above)
Comment (treeowl) [reply src/BinomialQueue/Internals.hs:216]: Done.

**Comment by treeowl** [comment]
I believe I've dealt with all your concerns.

File: src/BinomialQueue/Internals.hs [hunk 4]
```diff
@@ -219,11 +228,24 @@ unions = foldl' union empty
 
 -- | \(O(n)\). Map elements and collect the 'Just' results.
 mapMaybe :: Ord b => (a -> Maybe b) -> MinQueue a -> MinQueue b
-mapMaybe f (MinQueue ts) = mapMaybeQueue f (const empty) empty ts
+mapMaybe f = flip foldlU' empty $ \q a ->
+  case f a of
+    Nothing -> q
+    Just b -> insertEager b q
+-- This seems to be needed for specialization.
```
Comment (konsumlamm) [inline src/BinomialQueue/Internals.hs:235]: Also see #94, most functions don't seem to be specialized.

File: src/Data/PQueue/Prio/Min.hs [hunk 5]
```diff
@@ -142,13 +142,6 @@ import qualified Data.PQueue.Prio.Internals as Internals
 
 import Prelude hiding (map, filter, break, span, takeWhile, dropWhile, splitAt, take, drop, (!!), null)
 
-#ifdef __GLASGOW_HASKELL__
-import GHC.Exts (build)
-#else
-build :: ((a -> [a] -> [a]) -> [a] -> [a]) -> [a]
-build f = f (:) []
-#endif
-
```
Comment (konsumlamm) [inline src/Data/PQueue/Prio/Min.hs:151]: Is this not used anymore or is it just to remove non-GHC stuff?

Comment (treeowl) [reply src/Data/PQueue/Prio/Min.hs:151]: It's not used in this module anymore. We still do it elsewhere, and this PR is not the place to deal with that.

File: src/BinomialQueue/Internals.hs (hunk 4 above)
Comment (treeowl) [reply src/BinomialQueue/Internals.hs:235]: Yeah, we need to deal with that. One step at a time ....

**Review by konsumlamm — APPROVED** [review]
