### PR TITLE
Pattern synonyms and Data instances

### LINKED ISSUE #50: Data instances are unsafe/wrong
It strikes me as somewhat peculiar that we have `Data` instances for priority queues at all, but if we're to do so, they should be consistent!

```haskell
{-# language ScopedTypeVariables, GADTs, TypeOperators, TypeApplications #-}

import Data.Data
import Data.Typeable
import Data.PQueue.Min

morp :: MinQueue Int -> MinQueue Int
morp = gmapT go
  where
    go :: forall d. Data d => d -> d
    go d
      | Just Refl <- eqT @d @Int
      = abs d
      | Just Refl <- eqT @d @(MinQueue Int)
      = d

main = print $ morp $ fromList [-5 .. 5]
```

This prints

```
fromAscList [5,-4,-3,-2,-1,0,1,2,3,4,5]
```

What's happening here? The `Data` instance for `MinQueue` (roughly speaking) pretends that we have

```haskell
data MinQueue a = empty | a <| MinQueue a
```

(Yes, those "constructor" names are lower case on purpose; that's basically okay.) The user can edit the "minimum value" and "the rest of the queue" independently, and the `Data` instance just assumes that the new minimum is in fact now greater than the minimal element of the new rest of the queue. That's ... peculiar.

----

Now we get to the inconsistency. `Data.PQueue.Prio.Min` has a similarly peculiar but totally *different* view of the structure of a priority queue! Specifically, it pretends we have (roughly)

```haskell
data MinpQueue a b = MinPQueue [(a, b)]
```

(but blows up if you try to *construct* a `MinPQueue` using `gunfold` or to inspect one using `toConstr`). Bzzwhat?

----

`MaxQueue` and `MaxPQueue` each use *derived* `Data` instances. That means they inherit all the peculiarities of the underlying instances, as well as revealing the relationships between the queue types. But wait! There's more! The `Down` type used to implement those types *isn't exported from the package*. This makes anything `syb`-style on it a bit ... awkward.

### Solutions

The easiest solution is to delete all the `Data` instances. I know, I know, that could break things. Other things we could do:

- 1\. Structure the `MinPQueue` instance more like the `MinQueue` instance. I think the latter is much nicer (because it doesn't force the queue to be completely rebuilt for no reason).
- 2a\. Make the instances preserve the queue invariants.
- 2b\. Document that the instances don't preserve the queue invariants.
- 3a\. Make the `MaxQueue` and `MaxPQueue` instances look like the `MinQueue` and `MinPQueue` ones.
- 3b\. Expose the internal `Down` type.
- 4\. Document how the instances behave.

I'm leaning toward 1, 2a, 4, and possibly 3a. I don't like 3b because if https://github.com/haskell/core-libraries-committee/issues/23 is accepted we'll eventually want to switch to `Data.Ord.Down`. I'm slightly nervous about 3a because I don't think there's any inherent reason that `MaxQueue` and `MaxPQueue` must forever be abstract.

### PR DESCRIPTION
**Pull request by treeowl**
* Add some pattern synonyms.
* Improve the `Data` instances to
  - Make the `MinPQueue` version incremental, like the `MinQueue` one.
  - Make all the instances respect the queue invariants.
* Use the pattern synonyms to explain the `Data` instances.

Fixes #50.

### CODE REVIEW

**Comment by treeowl** [comment]
@konsumlamm I suspect we'll want similar pattern synonyms for max-queues, but do we want

```haskell
(:>) :: Ord a => MaxQueue a -> a -> MaxQueue a
```

or

```haskell
(<:) :: Ord a => a -> MaxQueue a -> MaxQueue a
```

I think the first option is clearer, since I think of the maximum as coming *after* the rest. But ergonomics will then be quite different between min-queues and max-queues, and I'm not sure how good that is. Hmmmmm....

Semi-separately: now that the `Ord` instance for `Data.Ord.Down` is decent, we should switch to it. We could then export `MaxQueue` and `MaxPQueue` concretely (with their constructors). Should they then use *derived* `Data` instances? I think that probably makes the most sense, but I'm not sure.

**Comment by treeowl** [comment]
@konsumlamm In case you didn't notice, I was hoping for a review of this.

**Comment by konsumlamm** [comment]
> @konsumlamm In case you didn't notice, I was hoping for a review of this.

I did notice, don't worry. It just takes some time to get into the issue again and I still have other things to do.

File: src/Data/PQueue/Internals.hs [hunk 1]
```diff
@@ -81,15 +81,20 @@ fromBare xs = case BQ.minView xs of
...
 instance (Ord a, Data a) => Data (MinQueue a) where
   gfoldl f z q = case minView q of
     Nothing      -> z Empty
     Just (x, q') -> z insert `f` x `f` q'
 
   gunfold k z c = case constrIndex c of
     1 -> z Empty
-    2 -> k (k (z insertMinQ))
-    _ -> error "gunfold"
+    2 -> k (k (z insert))
```
Comment (konsumlamm) [inline src/Data/PQueue/Internals.hs:96]: Is the double `k` correct? It looks a bit suspicious to me.

**Review by konsumlamm — COMMENTED** [review]
Again, I don't know much about `Data`, so I'm just looking if things feel right.

**Comment by konsumlamm** [comment]
I'm reluctant about the pattern synonyms, as they're not O(1) (while standard patterns are) and people might expect them to be, unknowingly introducing a slowdown.

Is there a problem with keeping the `Constr`s as is?

**Comment by konsumlamm** [comment]
Btw, if you have time, could you take a look if #55 can be closed?

File: src/Data/PQueue/Prio/Internals.hs [hunk 2]
```diff
@@ -80,22 +80,37 @@ build f = f (:) []
...
+
+  dataCast1 x = gcast1 x
+
+  toConstr q
+    | null q = emptyConstr
+    | otherwise = consConstr
+
   dataTypeOf _ = queueDataType
-  dataCast1 f  = gcast1 f
-  dataCast2 f  = gcast2 f
```
[the remark this answers is not in the document]
Comment (treeowl) [reply src/Data/PQueue/Prio/Internals.hs:91]: Definitely a mistake. Thanks for catching it.

**Comment by treeowl** [comment]
@konsumlamm I think I've addressed all the issues. I would like to squash the commits rather than merging them.

**Comment by treeowl** [comment]
> Is there a problem with keeping the `Constr`s as is?

I really don't like the inconsistency between the way the plain versions and `Prio` versions conceptualize their types. I also think it's much easier to "explain" the `Data` instances by reference to bidirectional patterns than by reference to plain functions (one of which doesn't even bother to exist). Since the `Data` instance for `MinQueue` was fairly broken from the jump, I'd be pretty surprised if anyone actually used them in any way that the proposed changes would break.

**Comment by konsumlamm** [comment]
Hmm, ok.

As for your question about `:>` vs `<:`, I don't really have an opinion on that. I'm fine with using `:>`, as that's similar to what `Data.Sequence` does.

Do you also want to improve the `Data` instances for max queues in this PR or leave that to a future PR?

**Comment by treeowl** [comment]
I don't want to make any decisions whatsoever about max queues in this PR. I'll open a new one for pattern synonyms for them.

**Comment by konsumlamm** [comment]
> I would like to squash the commits rather than merging them intact.

That's what I always do anyway.

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,5 +1,15 @@
 # Revision history for pqueue
 
+## 1.5.0
+
+  * Add pattern synonyms to work with `MinQueue` and `MinPQueue`.
+    ([#92](http://github.com/lspitzner/pqueue/pull/92))
+
+  * Make the `Data` instances respect the queue invariants. Make the
+    `Constructor`s match the pattern synonyms. Make the `Data` instance for
```
Comment (konsumlamm) [inline CHANGELOG.md:9]:
```suggestion
    `Constr`s match the pattern synonyms. Make the `Data` instance for
```

**Comment by treeowl** [comment]
Are you ready to approve?

**Review by konsumlamm — APPROVED** [review]
